import { AspectRatio, Theme, SlideTemplate, AnimationEffect } from '../types';

export const ASPECT_RATIOS: AspectRatio[] = [
  { label: '16:9 (Widescreen)', value: '16:9', width: 1920, height: 1080 },
  { label: '16:10 (Computer)', value: '16:10', width: 1920, height: 1200 },
  { label: '1:1 (Square)', value: '1:1', width: 1080, height: 1080 },
  { label: '3:2 (Classic)', value: '3:2', width: 1620, height: 1080 },
  { label: '9:16 (Mobile)', value: '9:16', width: 1080, height: 1920 },
  { label: '10:16 (Tall)', value: '10:16', width: 1200, height: 1920 },
];

export const DEFAULT_THEMES: Theme[] = [
  // Original vibrant themes
  { primary: '#3B82F6', secondary: '#1E40AF', accent: '#F59E0B' },
  { primary: '#10B981', secondary: '#047857', accent: '#EF4444' },
  { primary: '#8B5CF6', secondary: '#5B21B6', accent: '#F97316' },
  { primary: '#F59E0B', secondary: '#D97706', accent: '#3B82F6' },
  { primary: '#EF4444', secondary: '#DC2626', accent: '#10B981' },
  { primary: '#6366F1', secondary: '#4338CA', accent: '#EC4899' },
  
  // Complementary color schemes
  { primary: '#FF6B6B', secondary: '#4ECDC4', accent: '#45B7D1' },
  { primary: '#96CEB4', secondary: '#FFEAA7', accent: '#DDA0DD' },
  { primary: '#74B9FF', secondary: '#FD79A8', accent: '#FDCB6E' },
  { primary: '#A29BFE', secondary: '#6C5CE7', accent: '#00B894' },
  
  // Dark themes
  { primary: '#1F2937', secondary: '#374151', accent: '#F59E0B' },
  { primary: '#111827', secondary: '#1F2937', accent: '#10B981' },
  { primary: '#0F172A', secondary: '#1E293B', accent: '#3B82F6' },
  { primary: '#18181B', secondary: '#27272A', accent: '#EF4444' },
  
  // Monochrome themes
  { primary: '#000000', secondary: '#404040', accent: '#808080' },
  { primary: '#FFFFFF', secondary: '#E5E5E5', accent: '#999999' },
  { primary: '#2D3748', secondary: '#4A5568', accent: '#718096' },
  { primary: '#F7FAFC', secondary: '#EDF2F7', accent: '#CBD5E0' },
  
  // Professional themes
  { primary: '#2C5282', secondary: '#2A4365', accent: '#ED8936' },
  { primary: '#2F855A', secondary: '#276749', accent: '#D69E2E' },
];

export const SLIDE_TEMPLATES: SlideTemplate[] = [
  { id: 'title-center', name: 'Title Center', preview: '📄', layout: 'title-center' },
  { id: 'title-left', name: 'Title Left', preview: '📋', layout: 'title-left' },
  { id: 'title-top', name: 'Title Top', preview: '📊', layout: 'title-top' },
  { id: 'split-content', name: 'Split Content', preview: '📑', layout: 'split-content' },
  { id: 'title-bottom', name: 'Title Bottom', preview: '📝', layout: 'title-bottom' },
  { id: 'title-right', name: 'Title Right', preview: '📰', layout: 'title-right' },
];

export const ANIMATION_EFFECTS: AnimationEffect[] = [
  { type: 'none', duration: 0, delay: 0 },
  { type: 'fadeIn', duration: 1000, delay: 0 },
  { type: 'slideInLeft', duration: 800, delay: 0 },
  { type: 'slideInRight', duration: 800, delay: 0 },
  { type: 'slideInUp', duration: 800, delay: 0 },
  { type: 'slideInDown', duration: 800, delay: 0 },
  { type: 'zoomIn', duration: 600, delay: 0 },
  { type: 'bounceIn', duration: 1200, delay: 0 },
];

export const PEXELS_PHOTOS = [
  'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  'https://images.pexels.com/photos/3184341/pexels-photo-3184341.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
];

export const FONT_FAMILIES = [
  'Inter, system-ui, sans-serif',
  'Roboto, sans-serif',
  'Open Sans, sans-serif',
  'Lato, sans-serif',
  'Montserrat, sans-serif',
  'Poppins, sans-serif',
  'Source Sans Pro, sans-serif',
  'Nunito, sans-serif',
  'Raleway, sans-serif',
  'Ubuntu, sans-serif',
];

export const TRANSLATIONS = {
  ko: {
    title: 'AI 슬라이드 생성기',
    content: '콘텐츠',
    contentPlaceholder: '프레젠테이션 내용을 입력하세요. 각 단락이 슬라이드가 됩니다...',
    themeColors: '테마 색상',
    slideAspectRatio: '슬라이드 비율',
    generateSlides: '슬라이드 생성',
    generating: '생성 중...',
    exportPDF: 'PDF 내보내기',
    exportHTML: 'HTML 내보내기',
    noSlidesGenerated: '아직 생성된 슬라이드가 없습니다',
    addContentAndGenerate: '콘텐츠를 추가하고 "슬라이드 생성"을 클릭하여 시작하세요',
    generatedSlides: '생성된 슬라이드',
    addSlide: '슬라이드 추가',
    addSlideHere: '여기에 슬라이드 추가',
    preview: '미리보기',
    html: 'HTML',
    editSlide: '슬라이드 편집',
    modificationRequest: 'AI 수정 요청',
    modificationPlaceholder: '이 슬라이드를 어떻게 수정하고 싶은지 설명하세요...',
    updateSlide: '슬라이드 업데이트',
    updating: '업데이트 중...',
    newSlide: '새 슬라이드',
    addContentHere: '여기에 콘텐츠를 추가하세요...',
    geminiApiKey: 'Gemini API 키',
    geminiApiKeyPlaceholder: 'Google Gemini API 키를 입력하세요',
    apiSettings: 'API 설정',
    saveApiKey: 'API 키 저장',
    apiKeyRequired: 'Gemini API 키가 필요합니다',
    language: '언어',
    korean: '한국어',
    english: 'English',
    templates: '템플릿',
    selectTemplate: '템플릿 선택',
    changeBackground: '배경 변경',
    uploadImage: '이미지 업로드',
    searchImages: '이미지 검색',
    searchImagesPlaceholder: '이미지를 검색하세요...',
    noImagesFound: '이미지를 찾을 수 없습니다',
    textProperties: '텍스트 속성',
    fontSize: '글자 크기',
    fontFamily: '글꼴',
    fontColor: '글자 색상',
    fontWeight: '글자 굵기',
    textAlign: '정렬',
    animation: '애니메이션',
    animationType: '애니메이션 유형',
    animationDuration: '지속 시간',
    animationDelay: '지연 시간',
    undo: '실행 취소',
    redo: '다시 실행',
    applyChanges: '변경사항 적용',
    saved: '저장됨',
    none: '없음',
    fadeIn: '페이드 인',
    slideInLeft: '왼쪽에서 슬라이드',
    slideInRight: '오른쪽에서 슬라이드',
    slideInUp: '아래에서 슬라이드',
    slideInDown: '위에서 슬라이드',
    zoomIn: '확대',
    bounceIn: '바운스',
    left: '왼쪽',
    center: '가운데',
    right: '오른쪽',
    normal: '보통',
    bold: '굵게',
    bolder: '더 굵게',
    borderStyle: '테두리 스타일',
    noBorder: '테두리 없음',
    cleanLine: '깔끔한 선',
    modernCard: '모던 카드',
    boldFrame: '굵은 프레임',
    dashedCreative: '점선 창의적',
    dottedPlayful: '점점 재미있는',
    doubleProfessional: '이중선 전문적',
    glowEffect: '글로우 효과',
    templateStyle: '템플릿 스타일',
    mixedAuto: '자동 혼합',
    mixedAutoDesc: '자동',
    presentationFormal: '정식 발표',
    presentationFormalDesc: '정형화',
    sideBySide: '좌우 분할',
    sideBySideDesc: '좌우분할',
    titleFocus: '제목 중심',
    titleFocusDesc: '제목중심',
    contentHeavy: '내용 중심',
    contentHeavyDesc: '내용중심',
    creativeAsymmetric: '크리에이티브',
    creativeAsymmetricDesc: '창의적',
    selected: '선택됨',
  },
  en: {
    title: 'AI Slide Generator',
    content: 'Content',
    contentPlaceholder: 'Enter your presentation content here. Each paragraph will become a slide...',
    themeColors: 'Theme Colors',
    slideAspectRatio: 'Slide Aspect Ratio',
    generateSlides: 'Generate Slides',
    generating: 'Generating...',
    exportPDF: 'Export PDF',
    exportHTML: 'Export HTML',
    noSlidesGenerated: 'No slides generated yet',
    addContentAndGenerate: 'Add content and click "Generate Slides" to get started',
    generatedSlides: 'Generated Slides',
    addSlide: 'Add Slide',
    addSlideHere: 'Add slide here',
    preview: 'Preview',
    html: 'HTML',
    editSlide: 'Edit Slide',
    modificationRequest: 'AI Modification Request',
    modificationPlaceholder: 'Describe how you want to modify this slide...',
    updateSlide: 'Update Slide',
    updating: 'Updating...',
    newSlide: 'New Slide',
    addContentHere: 'Add your content here...',
    geminiApiKey: 'Gemini API Key',
    geminiApiKeyPlaceholder: 'Enter your Google Gemini API key',
    apiSettings: 'API Settings',
    saveApiKey: 'Save API Key',
    apiKeyRequired: 'Gemini API key is required',
    language: 'Language',
    korean: '한국어',
    english: 'English',
    templates: 'Templates',
    selectTemplate: 'Select Template',
    changeBackground: 'Change Background',
    uploadImage: 'Upload Image',
    searchImages: 'Search Images',
    searchImagesPlaceholder: 'Search for images...',
    noImagesFound: 'No images found',
    textProperties: 'Text Properties',
    fontSize: 'Font Size',
    fontFamily: 'Font Family',
    fontColor: 'Font Color',
    fontWeight: 'Font Weight',
    textAlign: 'Text Align',
    animation: 'Animation',
    animationType: 'Animation Type',
    animationDuration: 'Duration',
    animationDelay: 'Delay',
    undo: 'Undo',
    redo: 'Redo',
    applyChanges: 'Apply Changes',
    saved: 'Saved',
    none: 'None',
    fadeIn: 'Fade In',
    slideInLeft: 'Slide In Left',
    slideInRight: 'Slide In Right',
    slideInUp: 'Slide In Up',
    slideInDown: 'Slide In Down',
    zoomIn: 'Zoom In',
    bounceIn: 'Bounce In',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    normal: 'Normal',
    bold: 'Bold',
    bolder: 'Bolder',
    borderStyle: 'Border Style',
    noBorder: 'No Border',
    cleanLine: 'Clean Line',
    modernCard: 'Modern Card',
    boldFrame: 'Bold Frame',
    dashedCreative: 'Dashed Creative',
    dottedPlayful: 'Dotted Playful',
    doubleProfessional: 'Double Professional',
    glowEffect: 'Glow Effect',
    templateStyle: 'Template Style',
    mixedAuto: 'Auto Mixed',
    mixedAutoDesc: 'Auto',
    presentationFormal: 'Formal Presentation',
    presentationFormalDesc: 'Formal',
    sideBySide: 'Side by Side',
    sideBySideDesc: 'Split',
    titleFocus: 'Title Focus',
    titleFocusDesc: 'Title',
    contentHeavy: 'Content Heavy',
    contentHeavyDesc: 'Heavy',
    creativeAsymmetric: 'Creative',
    creativeAsymmetricDesc: 'Creative',
    selected: 'Selected',
  },
};